# Generated by Django 2.2.12 on 2021-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20210326_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profile_picture'),
        ),
    ]
